#!/usr/bin/env python3

from pathlib import Path
import csv
import html
from datetime import datetime


INPUT_CSV = Path("assets/data/reviews.csv")
OUTPUT_HTML = Path("_includes/reviews.html")


HEADER = """<!-- Generated by review_generate.py. Do not edit this file directly. -->
<section id="google-reviews" class="reviews-carousel-section reveal-on-scroll" aria-labelledby="reviews-carousel-title">
  <div class="reviews-carousel-section__header">
    <p class="reviews-carousel-section__label">Google reviews</p>
    <h2 id="reviews-carousel-title">What clients say about Solo Studios</h2>
    <p>Selected reviews from clients who booked live saxophone, DJ sets and event music.</p>
  </div>

  <div class="reviews-carousel" data-reviews-carousel="true">
    <button class="reviews-carousel__button reviews-carousel__button--prev" type="button" data-review-prev="true" aria-label="Previous review">
      ‹
    </button>

    <div class="reviews-carousel__viewport" data-review-viewport="true" tabindex="0">
      <div class="reviews-carousel__track">
"""

FOOTER = """
      </div>
    </div>

    <button class="reviews-carousel__button reviews-carousel__button--next" type="button" data-review-next="true" aria-label="Next review">
      ›
    </button>
  </div>
</section>
"""


def format_date(date_string: str) -> str:
    """Convert YYYY-MM-DD to DD Mon YYYY."""
    date_string = date_string.strip()

    if not date_string:
        return ""

    try:
        return datetime.strptime(date_string, "%Y-%m-%d").strftime("%d %b %Y")
    except ValueError:
        return html.escape(date_string)


def build_review(review: dict, index: int) -> str:
    """Build the HTML for a single review card."""

    name = html.escape(
        review.get("reviewer_name", "").strip()
    )

    review_text = html.escape(
        review.get("review_text", "").strip()
    )

    event_type = html.escape(
        review.get("event_type", "").strip()
    )

    review_date = format_date(
        review.get("review_date", "")
    )

    # Parse and validate rating.
    try:
        rating = int(review.get("rating", 5))
    except (TypeError, ValueError):
        rating = 5

    # Keep ratings within the expected 1–5 range.
    rating = max(1, min(rating, 5))

    # Escape the URL before putting it into HTML.
    review_url = html.escape(
        review.get("review_url", "").strip(),
        quote=True,
    )

    stars = "★" * rating

    output = f"""
        <article class="review-card" aria-label="Google review {index}">
          <div class="review-card__stars" aria-label="{rating} out of 5 stars">
            {stars}
          </div>

          <blockquote class="review-card__quote">
            “{review_text}”
          </blockquote>

          <footer class="review-card__footer">
            <div class="review-card__person">
              <strong>{name}</strong>
              <span>{event_type} · {review_date}</span>
            </div>
"""

    if review_url:
        output += f"""
            <a
              class="review-card__link"
              href="{review_url}"
              target="_blank"
              rel="noopener noreferrer"
            >
              See this review on Google
            </a>
"""

    output += """          </footer>
        </article>
"""

    return output


def main() -> None:
    """Read reviews from CSV and generate the HTML file."""

    if not INPUT_CSV.exists():
        raise FileNotFoundError(
            f"Input CSV not found: {INPUT_CSV}"
        )

    with INPUT_CSV.open(
        "r",
        encoding="utf-8",
        newline="",
    ) as f:
        reader = csv.DictReader(f)
        reviews = list(reader)

    html_parts = [HEADER]

    for index, review in enumerate(reviews, start=1):
        html_parts.append(
            build_review(review, index)
        )

    html_parts.append(FOOTER)

    OUTPUT_HTML.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with OUTPUT_HTML.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as f:
        f.write("".join(html_parts))

    print(
        f"Generated {OUTPUT_HTML} from {INPUT_CSV}"
    )


if __name__ == "__main__":
    main()

